x

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 set -uo pipefail -o noclobber -o nounset
+#set -euxo pipefail
 shopt -s inherit_errexit
 #set -x
 
@@ -12,6 +13,7 @@ handle_error() {
 }
 
 trap 'handle_error "$?" "${BASH_COMMAND:-?}" "${FUNCNAME[0]:-main}(${BASH_SOURCE[0]:-?}:${LINENO:-?})"' ERR
+#trap 'echo Program failed! Error at line $LINENO' ERR
 
 sudo apt install moreutils
 
@@ -24,7 +26,9 @@ if [[ ! -d "var/queues" ]]; then
 	cp "installation/queues-templates/"* "var/queues"
 fi
 
-# shellcheck disable=SC2016
-echo 'source -- "$HOME/bin/applications/undownloader/configuration/aliases"' >> "$HOME/.bash_aliases"
+mkdir --parents "$HOME/applications"
+echo 'source -- "$HOME/applications/undownloader/configuration/aliases"' >> "$HOME/.bash_aliases"
+echo 'PATH="$HOME/applications/undownloader/bin:$PATH"' >> "$HOME/.bashrc"
+
 set +x
-echo -ne "\n\nSUCCESS!\n"
+echo -ne "\n\nSUCCESS!\n\n"
